# Docker Compose (./docker-compose.yml)
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./tennis_coaching_db.backup:/tennis_coaching_db.backup
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  backend:
    build: .
    command: flask run --host=0.0.0.0
    environment:
      # Flask Configuration
      FLASK_APP: ${FLASK_APP}
      FLASK_ENV: ${FLASK_ENV}
      FLASK_RUN_PORT: ${FLASK_RUN_PORT}
      FLASK_RUN_HOST: ${FLASK_RUN_HOST}
      FLASK_DEBUG: ${FLASK_DEBUG}
      
      # Database Configuration
      DATABASE_URL: ${DATABASE_URL}
      
      # AWS Credentials
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      
      # AWS Cognito Configuration
      AWS_COGNITO_REGION: ${AWS_COGNITO_REGION}
      AWS_COGNITO_USER_POOL_ID: ${AWS_COGNITO_USER_POOL_ID}
      AWS_COGNITO_CLIENT_ID: ${AWS_COGNITO_CLIENT_ID}
      AWS_COGNITO_CLIENT_SECRET: ${AWS_COGNITO_CLIENT_SECRET}
      COGNITO_DOMAIN: ${COGNITO_DOMAIN}
      
      # AWS S3 Configuration
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_REGION: ${AWS_S3_REGION}
      
      # AWS SES Configuration
      AWS_SES_REGION: ${AWS_SES_REGION}
      AWS_SES_SENDER: ${AWS_SES_SENDER}
    volumes:
      - .:/app 
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build: 
      context: .
      dockerfile: client/Dockerfile
    environment:
      VITE_API_URL: "http://localhost:8000"
    volumes:
      - ./client:/app  
      - /app/node_modules 
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: