"""Updating registers 2

Revision ID: 0f1cc874588a
Revises: 92f90a8cbbef
Create Date: 2025-03-29 21:57:49.863824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f1cc874588a'
down_revision = '92f90a8cbbef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('predicted_attendance', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register_entry', schema=None) as batch_op:
        batch_op.drop_column('predicted_attendance')

    # ### end Alembic commands ###
