"""removing emails from report template

Revision ID: 123fd5c3b381
Revises: 0017759540e4
Create Date: 2024-12-22 23:45:37.945929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123fd5c3b381'
down_revision = '0017759540e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_template', schema=None) as batch_op:
        batch_op.drop_column('email_subject_template')
        batch_op.drop_column('email_body_template')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_body_template', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email_subject_template', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
