"""resetting back to previous state

Revision ID: 1a39bf74c84c
Revises: f93d35dfb8f1
Create Date: 2024-12-25 16:43:13.799037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a39bf74c84c'
down_revision = 'f93d35dfb8f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('programme_players_session_id_fkey', 'programme_players', type_='foreignkey')
    op.drop_table('period_session')
    with op.batch_alter_table('programme_players', schema=None) as batch_op:
        batch_op.drop_constraint('programme_players_session_id_fkey', type_='foreignkey')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programme_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('programme_players_session_id_fkey', 'period_session', ['session_id'], ['id'])

    op.create_table('period_session',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teaching_period_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', postgresql.ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='dayofweek'), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('max_capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tennis_club_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['teaching_period_id'], ['teaching_period.id'], name='period_session_teaching_period_id_fkey'),
    sa.ForeignKeyConstraint(['tennis_club_id'], ['tennis_club.id'], name='period_session_tennis_club_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='period_session_pkey')
    )
    # ### end Alembic commands ###
