"""Session Planning Change Tables

Revision ID: 33b86b65f5de
Revises: 82b83e5f5646
Create Date: 2025-07-15 08:22:13.554176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b86b65f5de'
down_revision = '82b83e5f5646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_time_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('teaching_period_id', sa.Integer(), nullable=False),
    sa.Column('tennis_club_id', sa.Integer(), nullable=False),
    sa.Column('planned_by_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_time_id'], ['tennis_group_times.id'], ),
    sa.ForeignKeyConstraint(['planned_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['teaching_period_id'], ['teaching_period.id'], ),
    sa.ForeignKeyConstraint(['tennis_club_id'], ['tennis_club.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_time_id', 'date', 'teaching_period_id', name='unique_session_plan')
    )
    with op.batch_alter_table('session_plan', schema=None) as batch_op:
        batch_op.create_index('idx_session_plan_club', ['tennis_club_id'], unique=False)
        batch_op.create_index('idx_session_plan_date', ['date'], unique=False)
        batch_op.create_index('idx_session_plan_group_time_date', ['group_time_id', 'date'], unique=False)
        batch_op.create_index('idx_session_plan_teaching_period', ['teaching_period_id'], unique=False)

    op.create_table('session_plan_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_plan_id', sa.Integer(), nullable=False),
    sa.Column('programme_player_id', sa.Integer(), nullable=False),
    sa.Column('planned_status', sa.Enum('PLANNED_PRESENT', 'PLANNED_ABSENT', 'TRIAL_PLAYER', 'MAKEUP_PLAYER', name='plannedattendancestatus'), nullable=False),
    sa.Column('player_type', sa.Enum('REGULAR', 'MAKEUP', 'TRIAL', name='playertype'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['programme_player_id'], ['programme_players.id'], ),
    sa.ForeignKeyConstraint(['session_plan_id'], ['session_plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_plan_id', 'programme_player_id', name='unique_plan_entry_player')
    )
    with op.batch_alter_table('session_plan_entry', schema=None) as batch_op:
        batch_op.create_index('idx_session_plan_entry_plan', ['session_plan_id'], unique=False)
        batch_op.create_index('idx_session_plan_entry_player', ['programme_player_id'], unique=False)

    op.create_table('trial_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_plan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_number', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('medical_information', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('planned_status', sa.Enum('PLANNED_PRESENT', 'PLANNED_ABSENT', 'TRIAL_PLAYER', 'MAKEUP_PLAYER', name='plannedattendancestatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_plan_id'], ['session_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trial_player', schema=None) as batch_op:
        batch_op.create_index('idx_trial_player_email', ['contact_email'], unique=False)
        batch_op.create_index('idx_trial_player_name', ['name'], unique=False)
        batch_op.create_index('idx_trial_player_session_plan', ['session_plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trial_player', schema=None) as batch_op:
        batch_op.drop_index('idx_trial_player_session_plan')
        batch_op.drop_index('idx_trial_player_name')
        batch_op.drop_index('idx_trial_player_email')

    op.drop_table('trial_player')
    with op.batch_alter_table('session_plan_entry', schema=None) as batch_op:
        batch_op.drop_index('idx_session_plan_entry_player')
        batch_op.drop_index('idx_session_plan_entry_plan')

    op.drop_table('session_plan_entry')
    with op.batch_alter_table('session_plan', schema=None) as batch_op:
        batch_op.drop_index('idx_session_plan_teaching_period')
        batch_op.drop_index('idx_session_plan_group_time_date')
        batch_op.drop_index('idx_session_plan_date')
        batch_op.drop_index('idx_session_plan_club')

    op.drop_table('session_plan')
    # ### end Alembic commands ###
