"""Updating report columns

Revision ID: 36c4681cc7ab
Revises: f5372ee8d547
Create Date: 2025-03-18 21:30:23.711314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c4681cc7ab'
down_revision = 'f5372ee8d547'
branch_labels = None
depends_on = None


def upgrade():
    # Add new columns to the report table
    op.add_column('report', sa.Column('is_draft', sa.Boolean(), nullable=True))
    op.add_column('report', sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True))
    
    # Update existing reports to have is_draft=False
    op.execute("UPDATE report SET is_draft = FALSE WHERE is_draft IS NULL")
    
    # Now make the column not nullable with a default
    op.alter_column('report', 'is_draft', nullable=False, server_default=sa.text('FALSE'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('is_draft')

    # ### end Alembic commands ###
