"""RateType change

Revision ID: 3eddda3a0ecd
Revises: 29569c0b0b40
Create Date: 2025-05-21 19:10:38.318038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3eddda3a0ecd'
down_revision = '29569c0b0b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaching_rate', schema=None) as batch_op:
        batch_op.alter_column('rate_type',
               existing_type=postgresql.ENUM('lead', 'assistant', 'admin', 'other', name='ratetype'),
               nullable=True,
               existing_server_default=sa.text("'other'::ratetype"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaching_rate', schema=None) as batch_op:
        batch_op.alter_column('rate_type',
               existing_type=postgresql.ENUM('lead', 'assistant', 'admin', 'other', name='ratetype'),
               nullable=False,
               existing_server_default=sa.text("'other'::ratetype"))

    # ### end Alembic commands ###
