"""Removing tennis club id

Revision ID: 40ffdbb7bdc8
Revises: e644cbaaf22e
Create Date: 2025-02-09 17:24:52.221519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40ffdbb7bdc8'
down_revision = 'e644cbaaf22e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint('fk_report_tennis_club_id', type_='foreignkey')
        batch_op.drop_column('tennis_club_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tennis_club_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fk_report_tennis_club_id', 'tennis_club', ['tennis_club_id'], ['id'])

    # ### end Alembic commands ###
