"""adding fields to student and programme players

Revision ID: 47356ee1f531
Revises: 0f1cc874588a
Create Date: 2025-04-12 15:26:07.673473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47356ee1f531'
down_revision = '0f1cc874588a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programme_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('walk_home', sa.Boolean(), nullable=True))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('medical_information', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('medical_information')
        batch_op.drop_column('emergency_contact_number')
        batch_op.drop_column('contact_number')

    with op.batch_alter_table('programme_players', schema=None) as batch_op:
        batch_op.drop_column('walk_home')

    # ### end Alembic commands ###
