"""Adding cancellation functionality

Revision ID: 4e63b5f595c7
Revises: efd70930408d
Create Date: 2025-06-15 11:13:25.204859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e63b5f595c7'
down_revision = 'efd70930408d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancellation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tennis_club_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('cancellation_type', sa.Enum('SESSION', 'DAY', 'WEEK', name='cancellationtype'), nullable=False),
    sa.Column('specific_date', sa.Date(), nullable=True),
    sa.Column('week_start_date', sa.Date(), nullable=True),
    sa.Column('week_end_date', sa.Date(), nullable=True),
    sa.Column('group_time_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['group_time_id'], ['tennis_group_times.id'], ),
    sa.ForeignKeyConstraint(['tennis_club_id'], ['tennis_club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cancellation', schema=None) as batch_op:
        batch_op.create_index('idx_cancellation_club_date', ['tennis_club_id', 'specific_date'], unique=False)
        batch_op.create_index('idx_cancellation_club_week', ['tennis_club_id', 'week_start_date', 'week_end_date'], unique=False)
        batch_op.create_index('idx_cancellation_group_time', ['group_time_id', 'specific_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('cancellation', schema=None) as batch_op:
        batch_op.drop_index('idx_cancellation_group_time')
        batch_op.drop_index('idx_cancellation_club_week')
        batch_op.drop_index('idx_cancellation_club_date')

    op.drop_table('cancellation')
    # ### end Alembic commands ###
