"""Adding document loading page

Revision ID: 5798f17071d5
Revises: e466e5d5f738
Create Date: 2025-06-23 07:04:37.197852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5798f17071d5'
down_revision = 'e466e5d5f738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_for_coach_id', sa.Integer(), nullable=False),
    sa.Column('tennis_club_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tennis_club_id'], ['tennis_club.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['uploaded_for_coach_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index('idx_document_active', ['is_active'], unique=False)
        batch_op.create_index('idx_document_category', ['category'], unique=False)
        batch_op.create_index('idx_document_club', ['tennis_club_id'], unique=False)
        batch_op.create_index('idx_document_coach', ['uploaded_for_coach_id'], unique=False)

    op.create_table('document_download_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('downloaded_by_id', sa.Integer(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['downloaded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_download_log', schema=None) as batch_op:
        batch_op.create_index('idx_download_log_date', ['downloaded_at'], unique=False)
        batch_op.create_index('idx_download_log_document', ['document_id'], unique=False)
        batch_op.create_index('idx_download_log_user', ['downloaded_by_id'], unique=False)

    op.create_table('document_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_type', sa.String(length=20), nullable=True),
    sa.Column('granted_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['granted_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'user_id', name='unique_document_user_permission')
    )
    with op.batch_alter_table('document_permission', schema=None) as batch_op:
        batch_op.create_index('idx_document_permission_user', ['user_id'], unique=False)



def downgrade():

    with op.batch_alter_table('document_permission', schema=None) as batch_op:
        batch_op.drop_index('idx_document_permission_user')

    op.drop_table('document_permission')
    with op.batch_alter_table('document_download_log', schema=None) as batch_op:
        batch_op.drop_index('idx_download_log_user')
        batch_op.drop_index('idx_download_log_document')
        batch_op.drop_index('idx_download_log_date')

    op.drop_table('document_download_log')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index('idx_document_coach')
        batch_op.drop_index('idx_document_club')
        batch_op.drop_index('idx_document_category')
        batch_op.drop_index('idx_document_active')

    op.drop_table('document')
    # ### end Alembic commands ###
