"""adding a logo column

Revision ID: 7049e69ddc4f
Revises: bb65b59a3e95
Create Date: 2025-01-04 16:36:37.269206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7049e69ddc4f'
down_revision = 'bb65b59a3e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tennis_club', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tennis_club', schema=None) as batch_op:
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###
