"""Session Planning Change

Revision ID: 82b83e5f5646
Revises: d43f4d689253
Create Date: 2025-07-15 08:09:44.165071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82b83e5f5646'
down_revision = 'd43f4d689253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club_feature', schema=None) as batch_op:
        batch_op.drop_index('idx_club_feature_name')
        batch_op.drop_index('idx_club_feature_tennis_club')

    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.alter_column('subscription_status',
               existing_type=postgresql.ENUM('TRIAL', 'ACTIVE', 'EXPIRED', 'SUSPENDED', name='subscriptionstatus'),
               nullable=True,
               existing_server_default=sa.text("'TRIAL'::subscriptionstatus"))

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('is_draft',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('last_email_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('last_email_status',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('is_draft',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.alter_column('subscription_status',
               existing_type=postgresql.ENUM('TRIAL', 'ACTIVE', 'EXPIRED', 'SUSPENDED', name='subscriptionstatus'),
               nullable=False,
               existing_server_default=sa.text("'TRIAL'::subscriptionstatus"))

    with op.batch_alter_table('club_feature', schema=None) as batch_op:
        batch_op.create_index('idx_club_feature_tennis_club', ['tennis_club_id'], unique=False)
        batch_op.create_index('idx_club_feature_name', ['feature_name'], unique=False)

    # ### end Alembic commands ###
