"""removing register status

Revision ID: 878c74d82001
Revises: 47356ee1f531
Create Date: 2025-04-15 19:15:19.631394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '878c74d82001'
down_revision = '47356ee1f531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('DRAFT', 'SUBMITTED', name='registerstatus'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
