"""Adding relationship to the programmeplayers table

Revision ID: 8c0de6a2754b
Revises: 0c2a363e73be
Create Date: 2024-12-25 18:13:47.591219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0de6a2754b'
down_revision = '0c2a363e73be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programme_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_time_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tennis_group_times', ['group_time_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programme_players', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('group_time_id')

    # ### end Alembic commands ###
