"""adding new capacity for session

Revision ID: 9c1cd0b4bc77
Revises: b6ef03a97a7b
Create Date: 2025-01-05 21:39:32.242006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1cd0b4bc77'
down_revision = 'b6ef03a97a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tennis_group_times', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tennis_group_times', schema=None) as batch_op:
        batch_op.drop_column('capacity')

    # ### end Alembic commands ###
