"""Adding assistant to regsiter

Revision ID: 9f16760a81a2
Revises: fd2f59652d5a
Create Date: 2025-05-17 16:47:02.353683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f16760a81a2'
down_revision = 'fd2f59652d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register_assistant_coach',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['register_id'], ['register.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('register_assistant_coach', schema=None) as batch_op:
        batch_op.create_index('idx_register_assistant_coach', ['register_id', 'coach_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register_assistant_coach', schema=None) as batch_op:
        batch_op.drop_index('idx_register_assistant_coach')

    op.drop_table('register_assistant_coach')
    # ### end Alembic commands ###
