"""adding recommended group to reports

Revision ID: ae94c1c84835
Revises: 123fd5c3b381
Create Date: 2024-12-24 08:11:36.047019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae94c1c84835'
down_revision = '123fd5c3b381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommended_group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tennis_group', ['recommended_group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('recommended_group_id')

    # ### end Alembic commands ###
