"""Enhanced email tracking on reports

Revision ID: b6ef03a97a7b
Revises: 7049e69ddc4f
Create Date: 2025-01-04 21:19:26.889905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b6ef03a97a7b'
down_revision = '7049e69ddc4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('email_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('email_message_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('email_message_id')
        batch_op.drop_column('email_history')
        batch_op.drop_column('email_recipients')

    # ### end Alembic commands ###
