"""adding new columns to period tables

Revision ID: bb65b59a3e95
Revises: 8c0de6a2754b
Create Date: 2024-12-29 22:09:42.724002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb65b59a3e95'
down_revision = '8c0de6a2754b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teaching_period', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_period_start_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('bookings_open_date', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teaching_period', schema=None) as batch_op:
        batch_op.drop_column('bookings_open_date')
        batch_op.drop_column('next_period_start_date')

    # ### end Alembic commands ###
