"""adding manage of features

Revision ID: e7fb53b8d78a
Revises: 4c16c8c1a2d8
Create Date: 2025-04-24 17:26:43.868143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7fb53b8d78a'
down_revision = '4c16c8c1a2d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tennis_club_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tennis_club_id'], ['tennis_club.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tennis_club_id', 'feature_name', name='unique_feature_per_club')
    )
    # ### end Alembic commands ###

    # Add indexes for performance
    op.create_index('idx_club_feature_tennis_club', 'club_feature', ['tennis_club_id'])
    op.create_index('idx_club_feature_name', 'club_feature', ['feature_name'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_club_feature_name')
    op.drop_index('idx_club_feature_tennis_club')
    op.drop_table('club_feature')
    # ### end Alembic commands ###
