"""adding paid functionality to model

Revision ID: fecb7503c2ca
Revises: f1dda367aeaa
Create Date: 2025-05-18 21:35:54.616371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fecb7503c2ca'
down_revision = 'f1dda367aeaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('paid_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['paid_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('paid_by_id')
        batch_op.drop_column('paid_at')

    # ### end Alembic commands ###
